### ISSUE TITLE
time.clock deprecated in Python 3.3+

### ISSUE THREAD

**Issue by ssardina** [ssardina-planning/p4-simulator#20]
When running with Python 3.8 I get:

![image](https://user-images.githubusercontent.com/2368384/112565410-1d3cd600-8e31-11eb-8e4b-a353e7b326af.png)

The reason is that `time.clock` has been deprecated:

![image](https://user-images.githubusercontent.com/2368384/112565464-334a9680-8e31-11eb-94bc-5106dda45509.png)

Manual: https://docs.python.org/3.7/library/time.html#time.clock

Check https://stackoverflow.com/questions/25785243/understanding-time-perf-counter-and-time-process-time

**Comment by freely-zz** [comment]
Hi Sebastian – p4 runs with python 2.7

 

From: Sebastian Sardina ***@***.***> 
Sent: Friday, 26 March 2021 12:46 PM
To: ssardina-planning/p4-simulator ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ssardina-planning/p4-simulator] time.clock deprecated in Python 3.3+ (#20)

 

When running with Python 3.8 I get:

 <https://user-images.githubusercontent.com/2368384/112565410-1d3cd600-8e31-11eb-8e4b-a353e7b326af.png> 

The reason is that time.clock has been deprecated:

 <https://user-images.githubusercontent.com/2368384/112565464-334a9680-8e31-11eb-94bc-5106dda45509.png> 

Check https://stackoverflow.com/questions/25785243/understanding-time-perf-counter-and-time-process-time

**Comment by ssardina** [comment]
Yes, correct. I am working on a branch to slowly migrate it to Python 3.8+. 

No rush, in another branch..

One of the things that 3.x has is OS independent timer!

**Comment by ssardina** [comment]
BTW, this is in branch `python-3.8`. I just got the first version of it working, but more checks and tweaks are needed so won't merge to master until then. Also want to check it works on Windows with the new taking of time.

**Comment by ssardina** [comment]
Done! It is working on Linux.. need to check in Windows..

**Comment by freely-zz** [comment]
I am in qld ATM and don't have access to any of this. I can check your version in Windows when I get back - next weds if that's any help. On 26 Mar 2021 8:14 pm, Sebastian Sardina ***@***.***> wrote:
Done! It is working on Linux.. need to check in Windows..

**Comment by ssardina** [comment]
ahhh what are you doing checking and replying to this then!  Enjoy QLD!!

**Comment by ssardina** [comment]
Done! It is now Python 3.8 compatible!
